#! /bin/bash

function is_root () {
    [ $(id -u) -ne 0 ]; echo $?
}

if [ $(is_root) -eq 0 ]; then
    echo "Please run as root : sudo ./install"
    exit 1
fi

script_name="potato"
install_path="/usr/local/bin/$script_name"

if [ "$1" == "-r" -a -e $install_path ]; then
    echo "Removing potato from $install_path"
    rm $install_path
elif [ -e $install_path ]; then
    if [ "$1" == "-f" ]; then
        echo "Installing potato to $install_path"
        cp $script_name $install_path
    else
        echo "Potato is already installed at $install_path"
    fi
else
    echo "Installing potato to $install_path"
    cp $script_name $install_path
fi