#! /bin/bash

if [ $# -ne 1 ]; then
	echo "Usage:   more-ram <size>"
	echo "Example: more-ram   9"
	exit
fi
echo "Downloading $1Gb of mp4 files..."
sleep 3
echo "Extracting..."
sleep 2
echo "Creating /dev/sbm..."
sleep 0.5
echo "Registering new bits..."
sleep 1
echo "Ram successfully added !"
echo "+$1Gb of ram"
