#! /bin/bash

function print_help () {
	echo "Potato laptop booster"
	echo "Commands:"
	echo "	add-ram	<size>			Increase the amount of ram by <size> Gb"
	echo "	enable-shell-rtx		Enable ray-traced shell"
	echo "	increase-resolution		Change screen resolution to 4K"
	echo "	add-cores				Increase CPU core count"
	echo "	add-cpu	<count>			Add <count> CPUs to the system"
	echo "	add-gpu					Add a GPU to the system"
	echo "	increase-disk <size>	Increase disk space by <size> Tb"
	echo "	optimize				Run various optimizations"
}

function char_n () {
	for i in $(seq 1 $1); do
		echo -n "$2"
	done
}

function random () {
	zero_one=$(echo "scale=20;$RANDOM/32767" | bc)
	range=$(echo "scale=20;$2-$1" | bc)
	echo $(echo "scale=20;$1+$zero_one*$range" | bc)
}

function rsleep () {
	sleep $(random $1 $2)
}

function loading () {
	echo -n $(char_n $1 "▯")
	for i in $(seq 1 $1); do
		rsleep 0.2 0.5
		echo -ne "\r"
		echo -n $(char_n $i "▮")
		echo -n $(char_n $(($1 - $i)) "▯")
	done
	echo
}

function add_ram () {
		echo "Choosing best RAM file format..."
		rsleep 0.75 1.25
		echo "Defaulting to .mp4 (most popular)"
		rsleep 0.25 0.75
		echo "Retrieving RAM providers list..."
		rsleep 0.75 1.25
		echo "Choosing best provider..."
		rsleep 0.25 0.75
		echo "Defaulting to https://freeram.ru"
		rsleep 0.1 0.3
		echo "Downloading RAM.mp4..."
		loading 25
		echo "Extracting..."
		rsleep 0.75 1.25
		echo "Setting up RAM..."
		rsleep 0.75 1.25
		echo "Creating /dev/ram0..."
		rsleep 0.25 0.75
		echo "Linking properties..."
		rsleep 0.75 1.25
		echo "Registering new kernel modules..."
		rsleep 1.5 2.5
		echo "Cleaning up..."
		rsleep 0.25 0.75
		echo -e "\nRAM successfully added !"
		echo "+$1Gb of RAM"
}

function enable_shell_rtx () {
		echo "Enabling ray-traced shell..."
		rsleep 0.75 1.25
		echo "Downloading RTX drivers..."
		loading 25
		echo "Extracting files..."
		loading 25
		echo "Checking compatibility..."
		rsleep 0.75 1.25
		echo "Computing checksum..."
		rsleep 1.75 2.25
		echo "Checksum is valid"
		rsleep 0.1 0.3
		echo "Running pre-install scripts..."
		rsleep 1.75 2.25
		echo "Installing..."
		loading 25
		echo "Compiling dependencies..."
		rsleep 1.75 2.25
		echo "Linking files..."
		rsleep 0.25 0.75
		echo "Running post-install scripts..."
		rsleep 1.75 2.25
		echo "Running post-post-install scripts..."
		rsleep 0.75 1.25
		echo "Configuring external metadata..."
		rsleep 0.25 0.75
		echo "Enabling..."
		rsleep 0.75 1.25
		echo -e "\nRTX shell successfully enabled !"
		echo "Note: this feature requires a dedicated GPU"
		echo "Note: you can install one by running 'potato add-gpu'"
}

function increase_resolution () {
	echo "Checking screen compatibility..."
	rsleep 0.75 1.25
	echo "Selecting screen reference..."
	rsleep 0.75 1.25
	echo "Calculating rasterization matrix..."
	rsleep 0.1 0.3
	echo "Downloading pixels from https://amaz0n.com..."
	loading 25
	echo "Resizing screen..."
	rsleep 0.75 1.25
	echo "Setting up new resolution..."
	rsleep 0.25 0.75
	echo "Adding colors..."
	rsleep 0.25 0.75
	echo "Calibrating..."
	rsleep 1.75 2.25
	echo "Removing useless pixels..."
	rsleep 0.75 1.25
	echo "Clearing standard output..."
	rsleep 0.25 0.75
	echo "Deleting old resolution..."
	rsleep 0.75 1.25
	echo -e "\nResolution successfully increased !"
	echo "Note: this feature requires a lot of RAM"
	echo "Note: you can install more by running 'potato add-ram <size>'"
}

function add_cores () {
	num_cores=$(nproc --all)
	echo "Retrieving CPU infos..."
	rsleep 0.75 1.25
	echo "CPU core count: $num_cores"
	echo "Target core count: $((num_cores * 2))"
	rsleep 0.75 1.25
	echo "Searching for new cores..."
	rsleep 0.25 0.75
	echo "Searching in /lost+found..."
	rsleep 0.25 0.75
	echo "Searching in /dev/null..."
	rsleep 0.25 0.75
	echo "No new cores found"
	sleep 1
	echo "Defaulting to core download"
	rsleep 0.5
	echo "Downloading cores from https://corehub.com..."
	loading 25
	echo "Unpacking core archive..."
	rsleep 1.75 2.25
	echo "Setting up virtual machine..."
	rsleep 0.75 1.25
	echo "Installing cores..."
	rsleep 1.75 2.25
	echo "Converting virtual machine to real machine..."
	rsleep 0.75 1.25
	echo "Setting up space on motherboard..."
	rsleep 0.25 0.75
	echo "Removed unused PCIe interfaces"
	rsleep 0.1 0.3
	echo "Connecting wires..."
	rsleep 0.75 1.25
	echo "Modifying BIOS configuration..."
	rsleep 2.5 3.5
	echo "Initializing L1 cache..."
	rsleep 0.25 0.75
	echo -e "\nCores successfully added !"
	echo "+$((num_cores)) cores"
}

if [ $# -eq 0 ]; then
	print_help
	exit
fi

case $1 in
	"add-ram")
		if [ $# -ne 2 ]; then
			print_help
			exit
		fi
		add_ram $2
		;;
	"enable-shell-rtx")
		enable_shell_rtx
		;;
	"increase-resolution")
		increase_resolution
		;;
	"add-cores")
		add_cores
		;;
esac
